services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}

  # for future deployment purpose
  
  # server:
  #   build: .
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db